version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - "3307:3306"
    networks:
      - my-shared-network
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  app-foyer:
    depends_on:
      mysqldb:
        condition: service_healthy  # Ensures MySQL is ready before Spring Boot starts
    image: hibaxbelghith/foyer-app
    restart: on-failure
    ports:
      - "8083:8081"
    networks:
      - my-shared-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

  angular-app:
    container_name: angular-app
    image: hibaxbelghith/angular-app
    restart: on-failure
    ports:
      - "4201:4200"
    networks:
      - my-shared-network
    depends_on:
      - app-foyer
    command: >
      bash -c "echo 'Angular App already built, serving static files with Nginx'"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    volumes:
      - /var/lib/jenkins/workspace/pipeline-angular/nginx.conf:/etc/nginx/nginx.conf  # Ensure this path is correct
      - /var/lib/jenkins/workspace/pipeline-angular/dist:/usr/share/nginx/html  # Ensure Angular's build files are here
    ports:
      - "80:80"  # Expose Nginx on port 80
    networks:
      - my-shared-network
    depends_on:
      - angular-app
      - app-foyer

volumes:
  db:

networks:
  my-shared-network: