version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3307:3306
    networks:
      - my-shared-network
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    depends_on:
      - mysqldb
    image: syrine2002/tp-foyerr:0.0.1
    restart: on-failure
    ports:
      - 8083:8089
    networks:
      - my-shared-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

  angular-app:
    container_name: angular-app
    image: syrine2002/angular-app:0.0.1  # Reference your pre-built Angular app image
    ports:
      - "4200:80"  # Expose internal port 80 to external port 4200
    networks:
      - my-shared-network
    restart: always

volumes:
  db:

networks:
  my-shared-network:
    driver: bridge
