version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3307:3306
    networks:
      - my-shared-network
    volumes:
      - db:/var/lib/mysql
  app-foyer:
    depends_on:
      - mysqldb
    image: hibaxbelghith/foyer-app
    #build : ./
    restart: on-failure
    ports:
      - 8083:8089
    networks:
      - my-shared-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'


    stdin_open: true
    tty: true

volumes:
  db :

networks:
  my-shared-network:
    #external: true
